Port 3000
Listen 127.0.0.1
Timeout 600
Allow 127.0.0.1
MaxClients 100

upstream none "telead.mail.name.ng"
upstream none "static.surfe.pro"
upstream none "telegram.org"
upstream none "www.google.com"
upstream none "t.me"
upstream none "android.clients.google.com"
upstream none "mtalk.google.com"
upstream none "accounts.google.com"

upstream http SmBEdeDq:UDXMyt49@gateway.aluvia.io:8080
