name: Full Setup Runner

on:
  workflow_dispatch:

jobs:
  run-all:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright
        run: |
          npm install imap-simple
          npm install mailparser
          npm install
          npx playwright install --with-deps

      - name: Install Xvfb
        run: sudo apt install -y xvfb

      - name: Run Node Script
        run: xvfb-run node secret.js
