name: Run Worker Sequentially

on:
  workflow_dispatch:

jobs:
  run-playwright:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        instance: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install expect
        run: |
          sudo apt update
          sudo apt install expect -y

      - name: Run workers with delay
        run: |
          chmod +x worker.exp

          ./worker.exp &
          sleep 5

          ./worker.exp &
          sleep 5

          ./worker.exp &

          wait
